---
#
# ─── INSTALL MARIADB ────────────────────────────────────────────────────────────
#
- name: Move MariaDB.repo to yum repo path
  template:
    src: MariaDB.repo.j2
    dest: /etc/yum.repos.d

- name: Install MariaDB
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
    - expect

# ────────────────────────────────────────────────────────────────────────────────
- name: Ensure service is started
  service:
    name: mariadb
    state: started
    enabled: yes
# ────────────────────────────────────────────────────────────────────────────────

#
# ─── DOWNLOAD MYSQL_SECURE INSTALLATION SCRIPT ──────────────────────────────────
#
- name: Download mysql_secure installation script
  get_url:
    url:https://gist.githubusercontent.com/rppf/b0930409cce6d2e2cfdfedc1b10c340e/raw/2bf89d10eb036227fc6050aca41fa35ab7e3fbdb/mysql_secure.sh
    dest: /tmp

#
# ─── RUN MYSQL_SECURE SCRIPT ────────────────────────────────────────────────────
#
- name: Run mysql_secure installation script
  shell: bash /tmp/mysql_secure.sh '"{{ mariadb_root_password }}"'

#
# ─── CREATE DATABASES ───────────────────────────────────────────────────────────
#
- name: Create user defined databases
  mysql_db:
    name: "{{ item.name }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present
  with_items: "{{ mariadb_databases }}"
  register: db_creation

#
# ─── CREATE USERS FOR MARIADB ───────────────────────────────────────────────────
#
- name: Create the users
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    host: localhost
    priv: "{{  database_name }}.*:ALL"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
