---
#
# ─── INSTALL MARIADB ────────────────────────────────────────────────────────────
#
- name: Move MariaDB.repo to yum repo path
  template:
    src: MariaDB.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo

- name: Install MariaDB
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - MariaDB-client
    - MariaDB-server
    - MySQL-python

# ────────────────────────────────────────────────────────────────────────────────
- name: Ensure service is started
  service:
    name: mariadb
    state: started
    enabled: yes
# ────────────────────────────────────────────────────────────────────────────────

#
# ─── SET ROOT PASSWORD ──────────────────────────────────────────────────────────
#
- name: Check if root password is set
  shell: >
    mysqladmin -u -root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: Set MariaDB root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes
    state: present
  when: root_pwd_check.rc == 0

#
# ─── CREATE DATABASES ───────────────────────────────────────────────────────────
#

- name: Remove the test database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent

- name: Create user defined databases
  mysql_db:
    name: "{{ item.name }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present
  with_items: "{{ mariadb_databases }}"
  register: db_creation

#
# ─── CREATE USERS FOR MARIADB ───────────────────────────────────────────────────
#
- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent

- name: Create the users
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    host: localhost
    priv: "{{  database_name }}.*:ALL"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present

# +-+-+-+-+ +-+-+-+-+-+-+-+-+ +-+-+ +-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+
# |C|o|p|y| |p|d|n|s|.|s|q|l| |t|o| |r|e|m|o|t|e| |m|a|c|h|i|n|e|s|
# +-+-+-+-+ +-+-+-+-+-+-+-+-+ +-+-+ +-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+
- name: Copy pdns.sql to remote machines
  copy:
    src: ../pdns.sql
    dest: /tmp/pdns.sql

# +-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+-+ +-+-+-+-+-+-+ +-+-+-+ +-+-+-+-+-+-+-+-+
# |I|n|s|e|r|t| |n|e|c|e|s|s|a|r|y| |t|a|b|l|e|s| |f|o|r| |P|o|w|e|r|D|N|S|
# +-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+-+ +-+-+-+-+-+-+ +-+-+-+ +-+-+-+-+-+-+-+-+
- name: Insert tables for PowerDNS
  mysql_db:
    name: "{{ database_name }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: import
    target: /tmp/pdns.sql