---
- name: Download NodeJS
  get_url:
    url: https://rpm.nodesource.com/setup_10.x
    dest: /tmp

- name: Setup NodeJS
  shell: bash - /tmp/setup_10.x

- name: Install NodeJS
  yum:
    name: nodejs
    state: latest
