---
- name: Download PowerDNS repo
  get_url:
    url: https://repo.powerdns.com/repo-files/centos-auth-41.repo
    dest: /etc/yum.repos.d/powerdns-auth-41.repo

- name: Download PowerDNS
  yum:
    name: pdns
    state: latest

- name: Download PowerDNS recursor repo
  get_url:
    url: https://repo.powerdns.com/repo-files/centos-rec-41.repo
    dest: /etc/yum.repos.d/powerdns-rec-41.repo

- name: Download PowerDNS recursor
  yum:
    name: pdns-recursor
    state: latest
