---
- name: Add PHP 7 repository
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- name: Install PHP 7
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - php72w
    - php72w-cli
    - php72w-common
    - php72w-mysql
    - php72w-gd
    - php72w-bcmath
    - php72w-mbstring
    - php72w-fpm
    - php72w-xml

- name: Ensure pool directory exists
  file:
    path: "{{ php_fpm_pool_conf_path | dirname}}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Ensure the pool exists
  template:
    src: www.conf.j2
    dest: "{{ php_fpm_pool_conf_path }}"
    owner: www-data
    group: www-data
    mode: 0644

- name: Configure php-fpm pool (if enabled).
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^user.?=.+$"
      line: "user = {{ php_fpm_pool_user }}"
    - regexp: "^group.?=.+$"
      line: "group = {{ php_fpm_pool_group }}"
    - regexp: "^listen.?=.+$"
      line: "listen = {{ php_fpm_listen }}"
    - regexp: '^listen\.allowed_clients.?=.+$'
      line: "listen.allowed_clients = {{ php_fpm_listen_allowed_clients }}"
    - regexp: '^pm\.max_children.?=.+$'
      line: "pm.max_children = {{ php_fpm_pm_max_children }}"
    - regexp: '^pm\.start_servers.?=.+$'
      line: "pm.start_servers = {{ php_fpm_pm_start_servers }}"
    - regexp: '^pm\.min_spare_servers.?=.+$'
      line: "pm.min_spare_servers = {{ php_fpm_pm_min_spare_servers }}"
    - regexp: '^pm\.max_spare_servers.?=.+$'
      line: "pm.max_spare_servers = {{ php_fpm_pm_max_spare_servers }}"
  notify: restart php-fpm

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer
  command: >
    php composer-installer.php {% if composer_version != ''%} --version={{ composer_version }}{% endif %}
    chdir=/tmp

- name: Move Composer into global location
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
