---
- name: Create a group www-data
  group:
    name: www-data
    state: present
    system: yes

- name: Create an user www-data
  user:
    name: www-data
    home: /var/www
    state: present
    group: www-data
    system: yes
    shell: /sbin/nologin

- name: Create a directory for your web files
  file:
    path: /var/www
    state: directory
    owner: www-data
    group: www-data
    mode: 0555

- name: Instal epel-release
  yum:
    name: epel-release
    state: latest

- name: Install firewalld
  yum:
    name: firewalld
    state: latest

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
