---
- name: Download & install redis
  yum:
    name: redis
    state: latest

- name: Enable redis service
  service:
    name: redis
    state: started
    enabled: yes

- name: Create a new zone named redis
  firewalld:
    zone: redis
    state: present
    permanent: yes

- name: Open port 6397
  firewalld:
    permanent: true
    zone: redis
    port: 6397/tcp
    state: enabled

- name: Reload firewall
  command: firewall-cmd --reload
