---
- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: installed

- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: Create a group www-data
  group:
    name: www-data
    state: present
    system: yes

- name: Create an user www-data
  user:
    name: www-data
    home: /var/www
    state: present
    group: www-data
    system: yes
    shell: sbin/nologin
    seuser: user_u

- name: Create a directory for your web files
  file:
    path: /var/www
    state: directory
    owner: www-data
    group: www-data
    mode: 0555
