---
- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
